# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Home.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Login import Ui_Login
from CoffeeShop import Ui_Coffee_Shop


class Ui_Home(object):

    def toLogin(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Login()
        self.ui.setupUi(self.window, self.thiswindow)
        self.thiswindow.close()
        self.window.show()

    def toShop(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Coffee_Shop()
        self.ui.setupUi(self.window, self.thiswindow)
        self.thiswindow.close()
        self.window.show()

    def setupUi(self, Home):
        Home.setObjectName("Home")
        Home.resize(423, 300)
        Home.setStyleSheet("background-color:#956F5D;\n"
                           "")
        self.btn_Customer = QtWidgets.QPushButton(Home)
        self.btn_Customer.setGeometry(QtCore.QRect(140, 140, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Kanit Light")
        font.setPointSize(12)
        self.btn_Customer.setFont(font)
        self.btn_Customer.setStyleSheet("background-color:#755F55;\n"
                                        "color:white;")
        self.btn_Customer.setObjectName("btn_Customer")
        self.btn_Manager = QtWidgets.QPushButton(Home)
        self.btn_Manager.setGeometry(QtCore.QRect(140, 210, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Kanit Light")
        font.setPointSize(12)
        self.btn_Manager.setFont(font)
        self.btn_Manager.setStyleSheet("background-color:#755F55;\n"
                                       "color:white;")
        self.btn_Manager.setObjectName("btn_Manager")
        self.label = QtWidgets.QLabel(Home)
        self.label.setGeometry(QtCore.QRect(20, 50, 381, 41))
        font = QtGui.QFont()
        font.setFamily("Kanit Light")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white;\n"
                                 "background-color:transparent;")
        self.label.setObjectName("label")

        # button click
        self.btn_Manager.clicked.connect(self.toLogin)
        self.btn_Customer.clicked.connect(self.toShop)


        self.thiswindow = Home
        self.retranslateUi(Home)
        QtCore.QMetaObject.connectSlotsByName(Home)

    def retranslateUi(self, Home):
        _translate = QtCore.QCoreApplication.translate
        Home.setWindowTitle(_translate("Home", "Home"))
        self.btn_Customer.setText(_translate("Home", "Customer"))
        self.btn_Manager.setText(_translate("Home", "Manager"))
        self.label.setText(_translate("Home", "Welcome to Roast Coffee Shop"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Home = QtWidgets.QDialog()
    ui = Ui_Home()
    ui.setupUi(Home)
    Home.show()
    sys.exit(app.exec_())
