# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Invoice.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from library.lib_query_order import getTotalPrice,getInvoice,Clearorder,getInvoiceforPrint
from library.lib_createhtml import createhtmlfile
import webbrowser
import os

class Ui_Invoice(object):

    def toHome(self):
        Clearorder()
        self.thiswindow.close()
        self.HomePage.show()

    def showDataInvoice(self, inputOrder):
        self.tb_Invoice.setRowCount(0)
        countitem = 0
        for rowdata in inputOrder:
            self.tb_Invoice.insertRow(countitem)
            countcol = 0
            for data in rowdata.values():
                self.tb_Invoice.setItem(countitem, countcol, QtWidgets.QTableWidgetItem('{}'.format(data)))
                countcol += 1
            countitem += 1


    def toPrint(self):
        dirpath = os.getcwd()
        createhtmlfile()
        webbrowser.open_new_tab("{0}/reports/invoiceID_{1}.html".format(dirpath,getInvoiceforPrint()[0]))

    def setupUi(self, Invoice, Home, Shop):
        Invoice.setObjectName("Invoice")
        Invoice.resize(543, 455)
        Invoice.setStyleSheet("background-color:#B99C8B;")
        self.tb_Invoice = QtWidgets.QTableWidget(Invoice)
        self.tb_Invoice.setGeometry(QtCore.QRect(20, 80, 371, 301))
        font = QtGui.QFont()
        font.setFamily("Kanit Light")
        font.setPointSize(11)
        self.tb_Invoice.setFont(font)
        self.tb_Invoice.setStyleSheet("background-color:white;")
        self.tb_Invoice.setObjectName("tb_Invoice")
        self.tb_Invoice.setColumnCount(5)
        self.tb_Invoice.setRowCount(0)
        self.tb_Invoice.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tb_Invoice.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)

        headerOr = self.tb_Invoice.horizontalHeader()
        headerOr.setSectionResizeMode(0, QtWidgets.QHeaderView.ResizeToContents)
        headerOr.setSectionResizeMode(1, QtWidgets.QHeaderView.ResizeToContents)
        headerOr.setSectionResizeMode(2, QtWidgets.QHeaderView.ResizeToContents)
        headerOr.setSectionResizeMode(3, QtWidgets.QHeaderView.ResizeToContents)
        headerOr.setSectionResizeMode(4, QtWidgets.QHeaderView.ResizeToContents)


        headerOr1 = QtWidgets.QTableWidgetItem("Name")
        headerOr2 = QtWidgets.QTableWidgetItem("Size")
        headerOr3 = QtWidgets.QTableWidgetItem("Price")
        headerOr4 = QtWidgets.QTableWidgetItem("Amount")
        headerOr5 = QtWidgets.QTableWidgetItem("Total")

        self.tb_Invoice.setHorizontalHeaderItem(0, headerOr1)
        self.tb_Invoice.setHorizontalHeaderItem(1, headerOr2)
        self.tb_Invoice.setHorizontalHeaderItem(2, headerOr3)
        self.tb_Invoice.setHorizontalHeaderItem(3, headerOr4)
        self.tb_Invoice.setHorizontalHeaderItem(4, headerOr5)



        self.label = QtWidgets.QLabel(Invoice)
        self.label.setGeometry(QtCore.QRect(20, 30, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Kanit Light")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:#755F55;\n"
                                 "border:1px;\n"
                                 "border-radius: 8px;\n"
                                 "color:white;")
        self.label.setObjectName("label")
        self.btn_Print = QtWidgets.QPushButton(Invoice)
        self.btn_Print.setGeometry(QtCore.QRect(420, 80, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Kanit Light")
        font.setPointSize(12)
        self.btn_Print.setFont(font)
        self.btn_Print.setStyleSheet("background-color:#755F55;\n"
                                     "color:white;")
        self.btn_Print.setObjectName("btn_Print")


        self.btn_Home = QtWidgets.QPushButton(Invoice)
        self.btn_Home.setGeometry(QtCore.QRect(420, 350, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Kanit Light")
        font.setPointSize(12)
        self.btn_Home.setFont(font)
        self.btn_Home.setStyleSheet("background-color:#755F55;\n"
                                    "color:white;")
        self.btn_Home.setObjectName("btn_Home")
        self.label_2 = QtWidgets.QLabel(Invoice)
        self.label_2.setGeometry(QtCore.QRect(190, 400, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Kanit Light")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color:#755F55;\n"
                                   "border:1px;\n"
                                   "border-radius: 8px;\n"
                                   "color:white;")
        self.label_2.setObjectName("label_2")

        self.showDataInvoice(getInvoice())

        # set page
        self.thiswindow = Invoice
        self.HomePage = Home
        self.ShopPage = Shop

        # button event
        self.btn_Home.clicked.connect(self.toHome)
        self.btn_Print.clicked.connect(self.toPrint)

        self.retranslateUi(Invoice)
        QtCore.QMetaObject.connectSlotsByName(Invoice)

    def retranslateUi(self, Invoice):
        _translate = QtCore.QCoreApplication.translate
        Invoice.setWindowTitle(_translate("Invoice", "Invoice"))
        self.label.setText(_translate("Invoice", " Your invoice"))
        self.btn_Print.setText(_translate("Invoice", "Print"))
        self.btn_Home.setText(_translate("Invoice", "Home"))
        self.label_2.setText(_translate("Invoice", " Total Price : {:,.2f} Baht.".format(getTotalPrice())))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Invoice = QtWidgets.QDialog()
    ui = Ui_Invoice()
    ui.setupUi(Invoice)
    Invoice.show()
    sys.exit(app.exec_())
