# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pymongo
import dns
import ctypes

MB_OK = 0x0
MB_OKCXL = 0x01
MB_YESNOCXL = 0x03
MB_YESNO = 0x04
MB_HELP = 0x4000
ICON_EXLAIM = 0x30
ICON_INFO = 0x40
ICON_STOP = 0x10
from CoffeeManger import Ui_ShowDataManager

Myserver = 'mongodb+srv://Chayapol:aum0825904216@cluster0.xjaok.mongodb.net/<dbname>?retryWrites=true&w=majority'


class Ui_Login(object):

    def toCoffeeManger(self, name):

        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_ShowDataManager()
        self.ui.setupUi(self.window, self.prewindow, name)
        self.thiswindow.hide()
        self.window.show()


    def checkLogin(self):
        username = str(self.txt_Username.text())
        password = str(self.txt_Password.text())
        with pymongo.MongoClient(Myserver) as conn:
            db = conn.get_database('Coffee_shop')
            where = {'$and': [{'username': username},
                              {'password': password}]}
            found = db.Admin.count_documents(where)
            cursor = db.Admin.find(where)

            name = ""
            for i in cursor:
                name = i['name']

            if found == 1:
                # ctypes.windll.user32.MessageBoxW(0, "Log-in success!!!", "Infomation", MB_OK | ICON_INFO)
                self.toCoffeeManger(name)
            else:
                ctypes.windll.user32.MessageBoxW(0, "Username or Password is incorrect!!!", "Warning", ICON_STOP)
                self.txt_Password.setText("")

    def setupUi(self, Login, Prewindow):
        Login.setObjectName("Login")
        Login.resize(400, 300)
        Login.setStyleSheet("background-color:#B99C8B;")
        self.label = QtWidgets.QLabel(Login)
        self.label.setGeometry(QtCore.QRect(100, 95, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Kanit Light")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:#755F55;\n"
                                 "border:1px;\n"
                                 "border-radius: 8px;\n"
                                 "color:white;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Login)
        self.label_2.setGeometry(QtCore.QRect(100, 165, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Kanit Light")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color:#755F55;\n"
                                   "border:1px;\n"
                                   "border-radius: 8px;\n"
                                   "color:white;")
        self.label_2.setObjectName("label_2")
        self.btn_Login = QtWidgets.QPushButton(Login)
        self.btn_Login.setGeometry(QtCore.QRect(230, 240, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Kanit Light")
        font.setPointSize(12)
        self.btn_Login.setFont(font)
        self.btn_Login.setStyleSheet("background-color:#755F55;\n"

                                     "color:white;")
        self.btn_Login.setObjectName("btn_Login")
        self.txt_Username = QtWidgets.QLineEdit(Login)
        self.txt_Username.setGeometry(QtCore.QRect(100, 130, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Kanit Light")
        font.setPointSize(12)
        self.txt_Username.setFont(font)
        self.txt_Username.setStyleSheet("background-color:white;")
        self.txt_Username.setObjectName("txt_Username")
        self.txt_Password = QtWidgets.QLineEdit(Login)
        self.txt_Password.setGeometry(QtCore.QRect(100, 200, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Kanit Light")
        font.setPointSize(12)
        self.txt_Password.setFont(font)
        self.txt_Password.setStyleSheet("background-color:white;")
        self.txt_Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_Password.setObjectName("txt_Password")
        self.label_3 = QtWidgets.QLabel(Login)
        self.label_3.setGeometry(QtCore.QRect(160, 20, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Kanit Light")
        font.setPointSize(22)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color:#755F55;\n"
                                   "border:1px;\n"
                                   "border-radius: 8px;\n"
                                   "color:white;")
        self.label_3.setObjectName("label_3")

        # button click
        self.btn_Login.clicked.connect(self.checkLogin)

        self.thiswindow = Login
        self.prewindow = Prewindow
        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Login"))
        self.label.setText(_translate("Login", " Username"))
        self.label_2.setText(_translate("Login", " Password"))
        self.btn_Login.setText(_translate("Login", "Log in"))
        self.label_3.setText(_translate("Login", " Log in"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QDialog()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())
